steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['deployment-manager', 'deployments', 'create', 'my-infra-deployment', '--config=deployment-config.yaml']
- name: 'ubuntu'
  entrypoint: bash
  args: ['-c', 'echo Deployment successful!']

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY

